import { authenticate, unauthenticated } from "../shopify.server";
import prisma from "../db.server";
import { fanOutServerSide } from "../lib/server-side.server";

// App Proxy entrypoint — Shopify signs and forwards /apps/pixelify-seo/<type> here.
//   llms.txt / llms-full.txt → deterministic catalog export (no content generation)
//   404                      → log a storefront miss for the redirect manager
//   track                    → server-side tracking ingest (fan out to GA4 MP / Meta CAPI)
export const loader = async ({ request, params }) => {
  const { session } = await authenticate.public.appProxy(request);
  const shopDomain = session?.shop ?? "";

  if (params.type === "llms.txt" || params.type === "llms-full.txt") {
    const s = await prisma.seoSettings.findUnique({ where: { shopDomain } });
    if (!s?.llmsTxtEnabled) return new Response("Not found", { status: 404 });
    // TODO: build the full catalog export via the Admin API. Stub keeps the route live.
    const body = `# ${shopDomain || "store"}\n# llms.txt — generated by pixelify-seo\n`;
    return new Response(body, { headers: { "Content-Type": "text/plain; charset=utf-8" } });
  }

  if (params.type === "robots.txt") {
    const s = await prisma.seoSettings.findUnique({ where: { shopDomain } });
    const body = (s?.robotsRules || "").trim() || "# Add robots rules in Pixelify SEO → Settings.";
    return new Response(body, { headers: { "Content-Type": "text/plain; charset=utf-8" } });
  }

  if (params.type === "indexnow") {
    const s = await prisma.seoSettings.findUnique({ where: { shopDomain } });
    if (!s?.indexnowKey) return new Response("Not found", { status: 404 });
    return new Response(s.indexnowKey, { headers: { "Content-Type": "text/plain; charset=utf-8" } });
  }

  if (params.type === "sitemap" || params.type === "sitemap.html") {
    if (!shopDomain) return new Response("Unauthorized", { status: 401 });
    const { admin } = await unauthenticated.admin(shopDomain);
    const res = await admin.graphql(
      `#graphql
      query { products(first: 100, query: "status:active") { nodes { handle title } } }`,
    );
    const json = await res.json();
    const items = (json.data?.products?.nodes ?? [])
      .map((n) => `<li><a href="https://${shopDomain}/products/${n.handle}">${n.title}</a></li>`)
      .join("");
    const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Sitemap</title></head><body><h1>Products</h1><ul>${items}</ul></body></html>`;
    return new Response(html, { headers: { "Content-Type": "text/html; charset=utf-8" } });
  }

  return new Response("Not found", { status: 404 });
};

export const action = async ({ request, params }) => {
  const { session } = await authenticate.public.appProxy(request);
  const shopDomain = session?.shop;
  if (!shopDomain) return new Response("Unauthorized", { status: 401 });

  if (params.type === "404") {
    const { path } = await request.json().catch(() => ({}));
    if (path) {
      await prisma.redirect404Log.upsert({
        where: { shopDomain_path: { shopDomain, path } },
        create: { shopDomain, path },
        update: { hits: { increment: 1 } },
      });
    }
    return new Response(null, { status: 204 });
  }

  if (params.type === "track") {
    const body = await request.json().catch(() => null);
    if (body) {
      await prisma.recentEvent.create({
        data: {
          shopDomain,
          name: body.event?.name ?? "event",
          platform: body.platform ?? null,
          payload: JSON.stringify(body).slice(0, 4000),
        },
      });
      // Cap the buffer to the 50 most recent per shop.
      const stale = await prisma.recentEvent.findMany({
        where: { shopDomain },
        orderBy: { createdAt: "desc" },
        skip: 50,
        select: { id: true },
      });
      if (stale.length) {
        await prisma.recentEvent.deleteMany({ where: { id: { in: stale.map((s) => s.id) } } });
      }
    }
    // Server-side fan-out (Pro): forward to GA4 Measurement Protocol / Meta CAPI.
    if (body?.event) {
      const settings = await prisma.trackingSettings.findUnique({ where: { shopDomain } });
      await fanOutServerSide(settings, body.event);
    }
    return new Response(null, { status: 204 });
  }
  return new Response("Not found", { status: 404 });
};
